const _tasks = {
    DEVELOPMENT: [{ value: 'General', label: 'General' },
    { value: 'Development', label: 'Development' },
    { value: 'Testing', label: 'Testing' },
    { value: 'Meeting', label: 'Meeting' },
    { value: 'Leading', label: 'Leading' },
    { value: 'Learning', label: 'Learning' },
    { value: 'Traning', label: 'Traning' },
    { value: 'Code Review', label: 'Code Review' },
    { value: 'Code Analysis', label: 'Code Analysis' },
    { value: 'Code Analysis', label: 'Code Analysis' },
    { value: 'Code Refactoring', label: 'Code Refactoring' },
    { value: 'Session', label: 'Session' },
    { value: 'Discussion', label: 'Discussion' },
    { value: 'Debugging', label: 'Debugging' },
    { value: 'Reporting', label: 'Reporting' },
    { value: 'Writing Docs', label: 'Writing Docs' },
    { value: 'Designing', label: 'Designing' },
    { value: 'Project Setup', label: 'Project Setup' },
    { value: 'Automated Testing', label: 'Automated Testing' },
    { value: 'Code Merging', label: 'Code Merging' }
    ],
    HR: [
        { value: 'Emailing', label: 'Emailing' },
        { value: 'Auditing', label: 'Auditing' },
        { value: 'Queries', label: 'Queries' },
        { value: 'Writing', label: 'Writing' },
        { value: 'Research', label: 'Research' },
        { value: 'Calling', label: 'Calling' },
        { value: 'Resume Screening', label: 'Resume Screening' },
        { value: 'Meeting', label: 'Meeting' },
        { value: 'Job Posting', label: 'Job Posting' },
    ]
}
export default _tasks