const _tasks = [
    { value: 'Miscellaneous', label: 'Miscellaneous' },
    { value: 'Administration-Missed Times', label: 'Administration-Missed Times' },
    { value: 'Administration-Admin Support', label: 'Administration-Admin Support' },
    { value: 'Finance-Billing and Sending Invoices', label: 'Finance-Billing and Sending Invoices' },
    { value: 'Finance-Cash Management', label: 'Finance-Cash Management' },
    { value: 'Finance-Employees Salaries', label: 'Finance-Employees Salaries' },
    { value: 'Finance-Financial Reporting', label: 'Finance-Financial Reporting' },
    { value: 'HR-Appointment Letter ', label: 'HR-Appointment Letter ' },
    { value: 'HR-Employee Development', label: 'HR-Employee Development' },
    { value: 'HR-Employee Issues Support ', label: 'HR-Employee Issues Support ' },
    { value: 'HR-Experience Letter ', label: 'HR-Experience Letter ' },
    { value: 'HR-Hiring Email Campaign', label: 'HR-Hiring Email Campaign' },
    { value: 'HR-Hiring Planning ', label: 'HR-Hiring Planning ' },
    { value: 'HR-Hiring Test', label: 'HR-Hiring Test' },
    { value: 'HR-Documentations', label: 'HR-Documentations' },
    { value: 'HR-Miscellaneous Work', label: 'HR-Miscellaneous Work' },
    { value: 'HR-Policies', label: 'HR-Policies' },
    { value: 'HR-Interviews', label: 'HR-Interviews' },
    { value: 'HR-New Employee', label: 'HR-New Employee' },
    { value: 'HR-Orientation', label: 'HR-Orientation' },
    { value: 'HR-Performance Appraisal', label: 'HR-Performance Appraisal' },
    { value: 'HR-PMO Work', label: 'HR-PMO Work' },
    { value: 'HR-Pre Interviews', label: 'HR-Pre Interviews' },
    { value: 'HR-Process Test Results', label: 'HR-Process Test Results' },
    { value: 'HR-Resume Shortlisting', label: 'HR-Resume Shortlisting ' },
    { value: 'HR-Schedule Interview', label: 'HR-Schedule Interview' },
    { value: 'IT-Customer Support', label: 'IT-Customer Support' },
    { value: 'IT-Documentation', label: 'IT-Documentation' },
    { value: 'IT-Environment Creation', label: 'IT-Environment Creation' },
    { value: 'IT-Fixing issues in Environment Setup', label: 'IT-Fixing issues in Environment Setup' },
    { value: 'IT-Issues', label: 'IT-Issues' },
    { value: 'IT-Outside Visit', label: 'IT-Outside Visit' },
    { value: 'IT-R&D', label: 'IT-R&D' },
    { value: 'IT-Review', label: 'IT-Review' },
    { value: 'IT-Server Management', label: 'IT-Server Management' },
    { value: 'IT-Task Working', label: 'IT-Task Working' },
    { value: 'SD-Analaysis FS Approval', label: 'SD-Analaysis FS Approval' },
    { value: 'SD-Analaysis FS Compilation', label: 'SD-Analaysis FS Compilation' },
    { value: 'SD-Analaysis FS Review', label: 'SD-Analaysis FS Review' },
    { value: 'SD-Analaysis R&D for Analysis', label: 'SD-Analaysis R&D for Analysis' },
    { value: 'SD-Analaysis Requirements Analysis and Gathering', label: 'SD-Analaysis Requirements Analysis and Gathering' },
    { value: 'SD-Analaysis Wireframe Creation', label: 'SD-Analaysis Wireframe Creation' },
    { value: 'SD-Design-Application Architecture', label: 'SD-Design-Application Architecture' },
    { value: 'SD-Design-Class Diagram Creation', label: 'SD-Design-Class Diagram Creation' },
    { value: 'SD-Design-DB Design', label: 'SD-Design-DB Design' },
    { value: 'SD-Design-R&D for Design', label: 'SD-Design-R&D for Design' },
    { value: 'SD-Design-TS Approval', label: 'SD-Design-TS Approval' },
    { value: 'SD-Design-TS Creation', label: 'SD-Design-TS Creation' },
    { value: 'SD-Design-TS Review', label: 'SD-Design-TS Review' },
    { value: 'SD-Development Coding', label: 'SD-Development Coding' },
    { value: 'SD-Development Coding Standards Creation', label: 'SD-Development Coding Standards Creation' },
    { value: 'SD-Development Deployments', label: 'SD-Development Deployments' },
    { value: 'SD-Development Front End Development', label: 'SD-Development Front End Development' },
    { value: 'SD-Development GUI Design', label: 'SD-Development GUI Design' },
    { value: 'SD-Development Implementation discussion with Customer', label: 'SD-Development Implementation discussion with Customer' },
    { value: 'SD-Development Implementation discussion with Team', label: 'SD-Development Implementation discussion with Team' },
    { value: 'SD-Development R&D to find a solution', label: 'SD-Development R&D to find a solution' },
    { value: 'SD-Development Refactoring', label: 'SD-Development Refactoring' },
    { value: 'SD-Development Troubleshooting Support to Team', label: 'SD-Development Troubleshooting Support to Team' },
    { value: 'SD-Development Unit Testing', label: 'SD-Development Unit Testing' },
    { value: 'SD-Monitoring Management Reports Review', label: 'SD-Monitoring Management Reports Review' },
    { value: 'SD-Monitoring Project Status Tracking', label: 'SD-Monitoring Project Status Tracking' },
    { value: 'SD-Monitoring Scrum Meeting', label: 'SD-Monitoring Scrum Meeting' },
    { value: 'SD-Monitoring Status discussion with Management', label: 'SD-Monitoring Status discussion with Management' },
    { value: 'SD-Monitoring State discussion with Team', label: 'SD-Monitoring State discussion with Team' },
    { value: 'SD-Monitoring Status Meeting with Customer ', label: 'SD-Monitoring Status Meeting with Customer ' },
    { value: 'SD-Monitoring Status Report', label: 'SD-Monitoring Status Report' },
    { value: 'SD-Monitoring Weekly Status Meeting', label: 'SD-Monitoring Weekly Status Meeting' },
    { value: 'SD-Planning CM Plan', label: 'SD-Planning CM Plan' },
    { value: 'SD-Planning Estimation', label: 'SD-Planning Estimation' },
    { value: 'SD-Planning Integration Plan', label: 'SD-Planning Integration Plan' },
    { value: 'SD-Planning IQA Plan', label: 'SD-Planning IQA Plan' },
    { value: 'SD-Planning Iteration Plan', label: 'SD-Planning Iteration Plan' },
    { value: 'SD-Planning Org/Dept Planning', label: 'SD-Planning Org/Dept Planning' },
    { value: 'SD-Planning Project Kickoff', label: 'SD-Planning Project Kickoff' },
    { value: 'SD-Planning Project Plan', label: 'SD-Planning Project Plan' },
    { value: 'SD-Planning Project Schedule', label: 'SD-Planning Project Schedule' },
    { value: 'SD-Planning RM Plan', label: 'SD-Planning RM Plan' },
    { value: 'SD-Planning Test Plan', label: 'SD-Planning Test Plan' },
    { value: 'SD-Planning Weekly Plan Creation', label: 'SD-Planning Weekly Plan Creation' },
    { value: 'SD-Review Code review', label: 'SD-Review Code review' },
    { value: 'SD-Review CRAP review', label: 'SD-Review CRAP review' },
    { value: 'SD-Review Functional review of an application', label: 'SD-Review Functional review of an application' },
    { value: 'SD-UAT Support UAT Changes', label: 'SD-UAT Support UAT Changes' },
    { value: 'SD-UAT Support UAT Changes Analysis', label: 'SD-UAT Support UAT Changes Analysis' },
    { value: 'SD-UAT Support UAT Changes Test Planning', label: 'SD-UAT Support UAT Changes Test Planning' },
    { value: 'SD-UAT Support UAT Changes Testing', label: 'SD-UAT Support UAT Changes Testing' },
    { value: 'SD-UAT Support UAT Defects Analysis', label: 'SD-UAT Support UAT Defects Analysis' },
    { value: 'SD-UAT Support UAT Defects Fixation', label: 'SD-UAT Support UAT Defects Fixation' },
    { value: 'SD-UAT Support UAT Defects Test Planning', label: 'SD-UAT Support UAT Defects Test Planning' },
    { value: 'SD-UAT Support UAT Defects Testing', label: 'SD-UAT Support UAT Defects Testing' },
    { value: 'SD-UAT Support UAT Shipment Assurance', label: 'SD-UAT Support UAT Shipment Assurance' },
    { value: 'SD-UAT Support UAT Test Case Review', label: 'SD-UAT Support UAT Test Case Review' },
    { value: 'SD-UAT Support UAT Testing Estimation', label: 'SD-UAT Support UAT Testing Estimation' },
    { value: 'SD-UAT Support UAT Testing Status Reporting', label: 'SD-UAT Support UAT Testing Status Reporting' },
    { value: 'Processes-Liaison with external parties', label: 'Processes-Liaison with external parties' },
    { value: 'Processes-PI Issues planning & tracking', label: 'Processes-PI Issues planning & tracking' },
    { value: 'Processes-Process definition', label: 'Processes-Process definition' },
    { value: 'Processes-Process Implementation Support ', label: 'Processes-Process Implementation Support ' },
    { value: 'Processes-Process Improvement Discussion', label: 'Processes-Process Improvement Discussion' },
    { value: 'Processes-Process Research', label: 'Processes-Process Research' },
    { value: 'Processes-SEPG', label: 'Processes-SEPG' },
    { value: 'QA-Customer Issues Discussion', label: 'QA-Customer Issues Discussion' },
    { value: 'QA-QA Improvements Work', label: 'QA-QA Improvements Work' },
    { value: 'QA-RCA Analysis of Issues', label: 'QA-RCA Analysis of Issues' },
    { value: 'Testing-Discussion Regarding Defects ', label: 'Testing-Discussion Regarding Defects ' },
    { value: 'Testing-Domain Understanding ', label: 'Testing-Domain Understanding ' },
    { value: 'Testing-Issue List Update or Review ', label: 'Testing-Issue List Update or Review ' },
    { value: 'Testing-Test Cases Creation', label: 'Testing-Test Cases Creation' },
    { value: 'Testing-Test Scenarios and Cases Review', label: 'Testing-Test Scenarios and Cases Review' },
    { value: 'Testing-Test Scenarios and Creation', label: 'Testing-Test Scenarios and Creation' },
    { value: 'Testing-Testing ', label: 'Testing-Testing ' },
    { value: 'Testing-Testing Estimation ', label: 'Testing-Testing Estimation ' },
    { value: 'Testing-Testing Status Reporting', label: 'Testing-Testing Status Reporting' },
    { value: 'Communication-Email Correspondence', label: 'Communication-Email Correspondence' },
    { value: 'Communication-Skype Meeting ', label: 'Communication-Skype Meeting ' },
    { value: 'Communication-Status Meeting with PM/TL', label: 'Communication-Status Meeting with PM/TL' },
    { value: 'Dev Log-Dev Log Creation', label: 'Dev Log-Dev Log Creation' },
    { value: 'Dev Log-Dev Log Review', label: 'Dev Log-Dev Log Review' },
    { value: 'Documentation-Project Profile Document', label: 'Documentation-Project Profile Document' },
    { value: 'Leave-Annual Leave', label: 'Leave-Annual Leave' },
    { value: 'Leave-Casual Leave', label: 'Leave-Casual Leave' },
    { value: 'Leave-Half Leave ', label: 'Leave-Half Leave ' },
    { value: 'Leave-Maternity Leave ', label: 'Leave-Maternity Leave ' },
    { value: 'Leave-Sick Leave', label: 'Leave-Sick Leave' },
    { value: 'Outage-Electricity Outage', label: 'Outage-Electricity Outage' },
    { value: 'Outage-Games/Socialize', label: 'Outage-Games/Socialize' },
    { value: 'Outage-Internet Outage', label: 'Outage-Internet Outage' },
    { value: 'Outage-Lunch/Prayers', label: 'Outage-Lunch/Prayers' },
    { value: 'Outage-Machine not working ', label: 'Outage-Machine not working ' },
    { value: 'Outage-Other Outrage', label: 'Outage-Other Outrage' },
    { value: 'Outage-Party ', label: 'Outage-Party ' },
    { value: 'Outage-Personal Work', label: 'Outage-Personal Work' },
    { value: 'Outage-Waiting for Task Assignment ', label: 'Outage-Waiting for Task Assignment ' },
    { value: 'Sales-Advertising ', label: 'Sales-Advertising ' },
    { value: 'Sales-Direct Marketing', label: 'Sales-Direct Marketing' },
    { value: 'Sales-Houses Inventory ', label: 'Sales-Houses Inventory ' },
    { value: 'Sales-Marketing Campaign ', label: 'Sales-Marketing Campaign ' },
    { value: 'Sales-Marketing Research ', label: 'Sales-Marketing Research ' },
    { value: 'Sales-Miscellaneous Work ', label: 'Sales-Miscellaneous Work ' },
    { value: 'Sales-Project Estimation ', label: 'Sales-Project Estimation ' },
    { value: 'Sales-Project Selection & Biding ', label: 'Sales-Project Selection & Biding ' },
    { value: 'Sales-SEO ', label: 'Sales-SEO ' },
    { value: 'Sales-SOW & Proposal Development', label: 'Sales-SOW & Proposal Development' },
    { value: 'SDM-Asana Management ', label: 'SDM-Asana Management ' },
    { value: 'SDM-Meeting with PMO ', label: 'SDM-Meeting with PMO ' },
    { value: 'SDM-Miscellaneous Work', label: 'SDM-Miscellaneous Work' },
    { value: 'SDM-Monthly Billing ', label: 'SDM-Monthly Billing ' },
    { value: 'SDM-Projects Status Report ', label: 'SDM-Projects Status Report ' },
    { value: 'SDM-Research ', label: 'SDM-Research ' },
    { value: 'SDM-Resource Allocation ', label: 'SDM-Resource Allocation ' },
    { value: 'SDM-Resource Reviews ', label: 'SDM-Resource Reviews ' },
    { value: 'SDM-Team Meeting', label: 'SDM-Team Meeting' },
    { value: 'Training-Discipline/Concept Training', label: 'Training-Discipline/Concept Training' },
    { value: 'Training-Domain Training ', label: 'Training-Domain Training ' },
    { value: 'Training-Job Card', label: 'Training-Job Card' },
    { value: 'Training-On Job Mentoring ', label: 'Training-On Job Mentoring ' },
    { value: 'Training-Process Training ', label: 'Training-Process Training ' },
    { value: 'Training-Self Study ', label: 'Training-Self Study ' },
    { value: 'Training-Technology Training ', label: 'Training-Technology Training ' },
    { value: 'Training-Training Preparation', label: 'Training-Training Preparation' },


]
export default _tasks